# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    paths: 
    - "src/**"
    - ".github/workflows/**"
  pull_request:
    branches: [ "main" ]
    paths: 
    - "src/**"
    - ".github/workflows/**"

jobs:
  build_core:
    name: Build Core
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/Core
        
    strategy:
      matrix:
        dotnet-version: [6.0.x, 7.0.x]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  

  build_example_library:
    name: Build Example library
    needs: build_core
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/ExampleLibrary
        
    strategy:
      matrix:
        dotnet-version: [6.0.x, 7.0.x]
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
  

  build_examples:
    name: Build Examples
    needs: build_example_library
    runs-on: ubuntu-latest
        
    strategy:
      matrix:
        dotnet-version: [6.0.x, 7.0.x]
        projects: [BasicBrainExample, FiniteExample, IndefiniteExample]

    defaults:
      run:
        working-directory: src/${{ matrix.projects }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
